In [5]:
# 1. Cargar la extensión de Kedro
%load_ext kedro.ipython

# 2. Ahora sí, inicializar el proyecto
%reload_kedro

[03/23/26 22:11:37] INFO     Using                                                                  ]8;id=801544;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=497874;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\framework\project\__init__.py#269\269]8;;\
                             'C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\f
                             ramework\project\rich_logging.yml' as logging configuration.

                    INFO     Registered line magic '%reload_kedro'                                   ]8;id=288206;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=686181;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py#64\64]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=537317;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=837584;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py#66\66]8;;\

                    INFO     Resolved project path as: C:\Users\maico\analisisdatoskedro.           ]8;id=527487;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=1707;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py#181\181]8;;\
                             To set a different path, run '%reload_kedro <project_root>'

[03/23/26 22:11:42] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=879040;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=597911;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro_telemetry\plugin.py#242\242]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

[03/23/26 22:11:43] INFO     Kedro project AnalisisDatosKedro                                       ]8;id=924082;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=589781;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py#147\147]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=18610;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=488221;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py#148\148]8;;\
                             'pipelines'

                    INFO     Registered line magic 'run_viz'                                        ]8;id=383297;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=466963;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py#154\154]8;;\

                    INFO     Resolved project path as: C:\Users\maico\analisisdatoskedro.           ]8;id=745169;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=608086;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py#181\181]8;;\
                             To set a different path, run '%reload_kedro <project_root>'

[03/23/26 22:11:45] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=103226;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=715512;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro_telemetry\plugin.py#242\242]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

                    INFO     Kedro project AnalisisDatosKedro                                       ]8;id=423922;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=31216;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py#147\147]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=565595;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=312060;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py#148\148]8;;\
                             'pipelines'

[03/23/26 22:11:46] INFO     Registered line magic 'run_viz'                                        ]8;id=764484;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=481429;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\ipython\__init__.py#154\154]8;;\

In [7]:
df = catalog.load("players_all")
df.tail()

[03/23/26 22:12:43] INFO     Loading data from players_all (ParquetDataset)...                 ]8;id=300628;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=870996;file://C:\Users\maico\analisisdatoskedro\kedro_env\lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
100990,245006,https://sofifa.com/player/245006/shuai-shao/20...,Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
100991,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
100992,252332,https://sofifa.com/player/252332/wei-zhang/20/...,Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
100993,251110,https://sofifa.com/player/251110/haijian-wang/...,Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
100994,233449,https://sofifa.com/player/233449/ximing-pan/20...,Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [13]:
columnas_interes = ['short_name', 'long_name', 'age', 'height_cm', 'weight_kg', 'nationality']
messi_data = df[df['long_name'].str.contains("Messi", case=False, na=False)]

# Mostrar los resultados
messi_data[columnas_interes]

,short_name,long_name,age,height_cm,weight_kg,nationality
0,L. Messi,Lionel Andrés Messi Cuccittini,27,169,67,Argentina
8098,Leandro,Leandro Messias dos Santos,30,183,77,Brazil
15465,L. Messi,Lionel Andrés Messi Cuccittini,28,170,72,Argentina
26291,Leandro,Leandro Messias dos Santos,31,183,77,Brazil
29064,J. Messi Enguene,Junior Messi Enguene,21,176,71,Cameroon
30347,L. Messi,Lionel Andrés Messi Cuccittini,29,170,72,Argentina
38090,Fabrício,Fabrício dos Santos Messias,26,182,78,Brazil
39635,Leandro,Leandro Messias dos Santos,32,183,77,Brazil
45098,N. Messiniti,Nicolás Messiniti,20,184,80,Argentina
47356,L. Messi,Lionel Andrés Messi Cuccittini,30,170,72,Argentina
54485,Fabrício,Fabrício dos Santos Messias,27,182,75,Brazil
58344,N. Messiniti,Nicolás Messiniti,21,184,80,Argentina
62018,Junior Messias,Junior Messias,26,174,66,Brazil
64948,L. Messi,Lionel Andrés Messi Cuccittini,31,170,72,Argentina
67006,Fabrício,Fabrício dos Santos Messias,28,183,78,Brazil
75885,N. Messiniti,Nicolás Messiniti,22,184,80,Argentina
77771,A. Messidoro,Alexis Messidoro,21,169,72,Argentina
82717,L. Messi,Lionel Andrés Messi Cuccittini,32,170,72,Argentina
84775,Fabrício,Fabrício dos Santos Messias,29,183,78,Brazil
88514,Messias,Messias Rodrigues Silva Jr.,24,192,88,Brazil

In [14]:
print(df.columns.tolist())

['sofifa_id', 'player_url', 'short_name', 'long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club', 'overall', 'potential', 'value_eur', 'wage_eur', 'player_positions', 'preferred_foot', 'international_reputation', 'weak_foot', 'skill_moves', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'team_position', 'team_jersey_number', 'loaned_from', 'joined', 'contract_valid_until', 'nation_position', 'nation_jersey_number', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_reflexes', 'gk_speed', 'gk_positioning', 'player_traits', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb']